
build:
	g++ *.cpp -std=c++20 -o ../../out/engine.dll -shared -DMH_BUILD_LIB -DMH_PLATFORM_WINDOWS -I../../vendor/spdlog/include
sdf:
	# g++ *.cpp -std=c++20 -o ../../out/engine.lib -static -DMH_BUILD_LIB
